#!/usr/bin/env python3
import base64
import sys

mode, val = sys.argv[1], sys.argv[2]
if mode == "b64dec":
    try:
        print(base64.b64decode(val, validate=True).hex())
    except Exception:
        print("REJECT")
elif mode == "b64enc":
    print(base64.b64encode(bytes.fromhex(val)).decode())
else:
    print("REJECT")
